
# generated by jobsub_lite
# 
universe           = vanilla
executable         = simple.sh
arguments          = --project=/pnfs/icarus/scratch/users/aanilkum/1muNp0pi_uncontained_project

output             = submit.sh2026_05_08_112739c3ad61c3-d2d1-419e-aaf4-679be3884eb8cluster.$(Cluster).$(Process).out
error              = submit.sh2026_05_08_112739c3ad61c3-d2d1-419e-aaf4-679be3884eb8cluster.$(Cluster).$(Process).err
log                = submit.sh2026_05_08_112739c3ad61c3-d2d1-419e-aaf4-679be3884eb8cluster.$(Cluster).$(Process).log


JOBSUBJOBSECTION=$(Process)

TRACEPARENT="00-76e35cc54e4a3b3fd09d107e8cb9da38-71ad9103d7e4e127-01"
+TraceParent=$(TRACEPARENT)

environment        = CM1=$(CM1);CM2=$(CM2);CLUSTER=$(Cluster);PROCESS=$(Process);JOBSUBJOBSECTION=$(JOBSUBJOBSECTION);CONDOR_TMP=/nashome/a/aanilkum/.cache/jobsub_lite/js_2026_05_08_112739_c3ad61c3-d2d1-419e-aaf4-679be3884eb8;BEARER_TOKEN_FILE=.condor_creds/icarus_1b78db904e.use;CONDOR_EXEC=/tmp;DAGMANJOBID=$(DAGManJobId);GRID_USER=aanilkum;JOBSUBJOBID=$(CLUSTER).$(PROCESS)@jobsub01.fnal.gov;EXPERIMENT=icarus;TRACEPARENT=00-76e35cc54e4a3b3fd09d107e8cb9da38-71ad9103d7e4e127-01;
rank               = Mips / 2 + Memory
job_lease_duration = 3600
transfer_output    = True
transfer_error     = True
transfer_executable= True
transfer_input_files = submit.sh
# if transfer_output_files is not explicitly set, condor will transfer ALL the files the job touches (unless in grid universe)
transfer_output_files = .empty_file
when_to_transfer_output = ON_EXIT_OR_EVICT


request_memory = 1800.0
request_disk = 26214400.0KB


+JobsubClientIpAddress="131.225.240.191"
+JobsubServerVersion="jobsub_lite-v1.12"
+JobsubClientVersion="jobsub_lite-v1.12"
+JobsubClientKerberosPrincipal="aanilkum@FNAL.GOV"
+JOB_EXPECTED_MAX_LIFETIME = 3600.0
notify_user = "aanilkum@fnal.gov"
notification = Never

# set command to user executable for jobsub_q
+JobsubCmd = "submit.sh"


+AccountingGroup = "group_icarus.aanilkum"


+Jobsub_Group="icarus"
+JobsubJobId="$(CLUSTER).$(PROCESS)@jobsub01.fnal.gov"
+JobsubOutputURL="https://fndcadoor.fnal.gov:2880/fermigrid/jobsub/jobs/2026_05_08/c3ad61c3-d2d1-419e-aaf4-679be3884eb8"
+JobsubUUID="c3ad61c3-d2d1-419e-aaf4-679be3884eb8"
+Drain = False
# default for remote submits is to keep completed jobs in the queue for 10 days
+LeaveJobInQueue = False


+DESIRED_SITES = ""


+GeneratedBy ="jobsub_lite-v1.12 jobsub01.fnal.gov"



+DESIRED_usage_model="DEDICATED,OPPORTUNISTIC,OFFSITE"


requirements = target.machine =!= MachineAttrMachine1 && target.machine =!= MachineAttrMachine2 && (isUndefined(DesiredOS) || stringListsIntersect(toUpper(DesiredOS),IFOS_installed)) && (stringListsIntersect(toUpper(target.HAS_usage_model), toUpper(my.DESIRED_usage_model))) && (TARGET.HAS_Singularity==true)


+SingularityImage="/cvmfs/singularity.opensciencegrid.org/fermilab/fnal-wn-sl7:latest"


#
# this is supposed to get us output even if jobs are held(?)
#
+SpoolOnEvict = false
#
#
#

# Credentials


use_oauth_services = icarus

icarus_oauth_permissions_1b78db904e = " compute.read compute.cancel compute.create compute.modify storage.read:/sbn storage.read:/numix storage.read:/icarus storage.read:/larsoft storage.create:/fermigrid/jobsub/jobs storage.read:/icarus/resilient/jobsub_stage storage.create:/icarus/scratch/users/aanilkum storage.create:/icarus/resilient/jobsub_stage storage.create:/icarus/persistent/users/aanilkum "





queue 1