
[[this_includes]]
file = '../configurations/common/variables.toml'

[[this_includes]]
file = '../configurations/common/styles.toml'

[samples]
[samples.mc]
key = "nominal"
exposure_type = "pot"
trees = ['selected']

[output]
path = '/Users/rvizarreta/Library/CloudStorage/GoogleDrive-rvizarreta14@gmail.com/My Drive/🏛 PhD Repository/🚀 Research/🤖 Experiments&Projects/ICARUS/ICARUS_CC0pi_Selection/ICARUS-NuMI-CC0pi-Selection/spineplot/myAnalysis/1muNp0pi_Nge1'

[analysis]
ordinate_sample = 'mc'
category_branch = 'true_category'
category_assignment = [[0], [1], [2], [3], [4], [5], [6]]
category_labels = ['1$\mu Np 0\pi$', '1$\mu 1p0 \pi$', '1$\mu 0p 0\pi$', 'Other CC','NC','Out of FV','Cosmic']
category_colors = ['C0', 'C1', 'C3','C4', 'C5', 'C6', 'C7']
category_types = ['histogram', 'histogram', 'histogram','histogram','histogram','histogram','histogram']

[[figure]]
name = 'true_category'
type = 'SimpleFigure'
style = 'selected_icarus_1muNp0pi_N>=1'
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'true_category'
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true, 'invert_stack_order' = false}

[[figure]]
name = 'true_visible_energy'
type = 'SimpleFigure'
style = 'selected_icarus_1muNp0pi_N>=1'
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'true_visible_energy'
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true, 'invert_stack_order' = false}

[[figure]]
name = 'reco_visible_energy'
type = 'SimpleFigure'
style = 'selected_icarus_1muNp0pi_N>=1'
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_visible_energy'
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true, 'invert_stack_order' = false}

[[figure]]
name = 'true_dpT'
type = 'SimpleFigure'
style = 'selected_icarus_1muNp0pi_N>=1'
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'true_dpT'
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true, 'invert_stack_order' = false}

[[figure]]
name = 'reco_dpT'
type = 'SimpleFigure'
style = 'selected_icarus_1muNp0pi_N>=1'
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_dpT'
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true, 'invert_stack_order' = false}

[[figure]]
name = 'reco_dphiT'
type = 'SimpleFigure'
style = 'selected_icarus_1muNp0pi_N>=1'
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_dphiT'
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true, 'invert_stack_order' = false}

[[figure]]
name = 'true_dphiT'
type = 'SimpleFigure'
style = 'selected_icarus_1muNp0pi_N>=1'
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'true_dphiT'
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true, 'invert_stack_order' = false}
