[[style]]
name = 'basic_icarus'
style_sheet = "/Users/rvizarreta/Library/CloudStorage/GoogleDrive-rvizarreta14@gmail.com/My Drive/🏛 PhD Repository/🚀 Research/🤖 Experiments&Projects/ICARUS/ICARUS_CC0pi_Selection/ICARUS-NuMI-CC0pi-Selection/spineplot/styles/muon2024.mplstyle"
markers = ['o', '^', 's', 'P', 'D']
default_figsize = [6.4,4.8]
title = ''
mark_pot = true
mark_preliminary = '$\bf{ICARUS}$ Work-in-Progress'
plot_kwargs = {'histtype' = 'barstacked', 'stacked' = true}

[[style]]
name = 'selected_icarus'
style_sheet = "/Users/rvizarreta/Library/CloudStorage/GoogleDrive-rvizarreta14@gmail.com/My Drive/🏛 PhD Repository/🚀 Research/🤖 Experiments&Projects/ICARUS/ICARUS_CC0pi_Selection/ICARUS-NuMI-CC0pi-Selection/spineplot/styles/muon2024.mplstyle"
markers = ['o', '^', 's', 'P', 'D']
default_figsize = [6.4,4.8]
title = '$\bf{ICARUS}$ $1\mu $ CC0$\pi$'
mark_pot = true
mark_preliminary = '$\bf{ICARUS}$ Work-in-Progress'
plot_kwargs = {'histtype' = 'barstacked', 'stacked' = true}

[[style]]
name = 'signal_icarus'
style_sheet = "/Users/rvizarreta/Library/CloudStorage/GoogleDrive-rvizarreta14@gmail.com/My Drive/🏛 PhD Repository/🚀 Research/🤖 Experiments&Projects/ICARUS/ICARUS_CC0pi_Selection/ICARUS-NuMI-CC0pi-Selection/spineplot/styles/muon2024.mplstyle"
markers = ['o', '^', 's', 'P', 'D']
default_figsize = [6.4,4.8]
title = '$\bf{ICARUS}$ $1\mu Np$ CC0$\pi$'
mark_pot = true
mark_preliminary = '$\bf{ICARUS}$ Simulation Work-in-Progress'
plot_kwargs = {'histtype' = 'barstacked', 'stacked' = true}

