[variables]

### Original Toml ------------------------

[variables.true_category]
key = "true_category"
range = [0, 9]
nbins = 9
xlabel = "Category"

[variables.true_visible_energy]
key = "true_visible_energy"
range = [0, 3]
nbins = 25
xlabel = "True Visible Energy [GeV]"

[variables.reco_visible_energy]
key = "reco_visible_energy"
range = [0, 3]
nbins = 25
xlabel = "Reco Visible Energy [GeV]"

### dpT ------------------------------------

[variables.true_dpT]
key = "true_dpT"
range = [0,1200]
nbins = 25
xlabel = 'True $\delta p_T$ [MeV/c]'

[variables.reco_dpT]
key = "reco_dpT"
range = [0,1200]
nbins = 25
xlabel = 'Reco $\delta p_T$ [MeV/c]'

[variables.reco_dpT_residual]
key = "reco_dpT"
range = [0,1200]
nbins = 200
xlabel = 'Reco $\delta p_T$ [MeV/c]'

[variables.true_dpT_residual]
key = "true_dpT"
range = [0,1200]
nbins = 200
xlabel = 'True $\delta p_T$ [MeV/c]'

[variables.reco_dpT_smearing]
key = "reco_dpT"
range = [0,1000]
nbins = 10
xlabel = 'Reco $\delta p_T$ [MeV/c]'

[variables.true_dpT_smearing]
key = "true_dpT"
range = [0,1000]
nbins = 10
xlabel = 'True $\delta p_T$ [MeV/c]'

### dalphaT ------------------------------------

[variables.true_dalphaT]
key = "true_dalphaT"
range = [0,4]
nbins = 25
xlabel = 'True $\delta \alpha_T$ [rad]'

[variables.reco_dalphaT]
key = "reco_dalphaT"
range = [0,4]
nbins = 25
xlabel = 'Reco $\delta \alpha_T$ [rad]'

[variables.reco_dalphaT_residual]
key = "reco_dalphaT"
range = [0,4]
nbins = 200
xlabel = 'Reco $\delta \alpha_T$ [rad]'

[variables.true_dalphaT_residual]
key = "true_dalphaT"
range = [0,4]
nbins = 200
xlabel = 'True $\delta \alpha_T$ [rad]'

[variables.reco_dalphaT_smearing]
key = "reco_dalphaT"
range = [0,4]
nbins = 10
xlabel = 'Reco $\delta \alpha_T$ [rad]'

[variables.true_dalphaT_smearing]
key = "true_dalphaT"
range = [0,4]
nbins = 10
xlabel = 'True $\delta \alpha_T$ [rad]'




[variables.true_dphiT]
key = "true_dphiT"
range = [0,4]
nbins = 25
xlabel = 'True $\delta \phi_T$ [MeV/c]'

[variables.reco_dphiT]
key = "reco_dphiT"
range = [0,4]
nbins = 25
xlabel = 'Reconstructed $\delta \phi_T$ [rad]'


[variables.reco_opening_angle]
key = "reco_opening_angle"
range = [0,4]
nbins = 25
xlabel = 'Reconstructed $\theta_{\mu p}$ [rad]'

[variables.reco_leading_muon_momentum]
key = "reco_leading_muon_momentum"
range = [0,10]
nbins = 25
xlabel = 'Reconstructed Leading Muon Momentum [GeV/c]'

[variables.reco_leading_muon_ke]
key = "reco_leading_muon_ke"
range = [0,2000]
nbins = 25
xlabel = 'Reconstructed Leading Muon Ke [MeV/c]'

[variables.true_leading_muon_ke]
key = "true_leading_muon_ke"
range = [0,2000]
nbins = 25
xlabel = 'True Leading Muon Ke [MeV/c]'

[variables.reco_leading_muon_ke_residual]
key = "reco_leading_muon_ke"
range = [0,2000]
nbins = 200
xlabel = 'Reconstructed Leading Muon Ke [MeV/c]'

[variables.true_leading_muon_ke_residual]
key = "true_leading_muon_ke"
range = [0,2000]
nbins = 200
xlabel = 'True Leading Muon Ke [MeV/c]'

[variables.reco_leading_muon_ke_smearing]
key = "reco_leading_muon_ke"
range = [0,2000]
nbins = 10
xlabel = 'Reconstructed Leading Muon Ke [MeV/c]'

[variables.true_leading_muon_ke_smearing]
key = "true_leading_muon_ke"
range = [0,2000]
nbins = 10
xlabel = 'True Leading Muon Ke [MeV/c]'